server:
  port: 8082
  servlet:
    contextPath: /auth-server

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wsfocux?useTimezone=true&serverTimezone=UTC
    username: root
    password: 12345
    
  jpa:
    #hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        temp.use_jdbc_metadata_defaults: false
 
logging:
  level:
    org.springframework.security.oauth2.provider.token.store: ERROR
    org.springframework.security.oauth2.provider.endpoint: ERROR
  